# TYPICAL STARTERS MAP (Primary 2025 Starters)
TYPICAL_STARTERS = {
    'ARI': 'K.Murray',
    'ATL': 'M.Penix',
    'BAL': 'L.Jackson',
    'BUF': 'J.Allen',
    'CAR': 'B.Young',
    'CHI': 'C.Williams',
    'CIN': 'J.Burrow',
    'CLE': 'S.Sanders',
    'DAL': 'D.Prescott',
    'DEN': 'B.Nix',
    'DET': 'J.Goff',
    'GB': 'J.Love',
    'HOU': 'C.Stroud',
    'IND': 'D.Jones',
    'JAX': 'T.Lawrence',
    'KC': 'P.Mahomes',
    'LA': 'M.Stafford',
    'LAC': 'J.Herbert',
    'LV': 'G.Smith',
    'MIA': 'T.Tagovailoa',
    'MIN': 'J.McCarthy',
    'NE': 'D.Maye',
    'NO': 'T.Shough',
    'NYG': 'J.Dart',
    'NYJ': 'B.Cook',
    'PHI': 'J.Hurts',
    'PIT': 'A.Rodgers',
    'SEA': 'S.Darnold',
    'SF': 'B.Purdy',
    'TB': 'B.Mayfield',
    'TEN': 'C.Ward',
    'WAS': 'J.Daniels'
}

# MANUAL OVERRIDE: [Backup Name, Wk1, Wk2, Wk3, Wk4...]
# True = Backup is starting, False = Typical Starter is playing
MANUAL_CURRENT_STARTERS = {
    'ARI': [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'ATL': [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'BAL': [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'BUF': [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'CAR': [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'CHI': [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'CIN': [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'CLE': [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'DAL': [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'DEN': [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'DET': [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'GB': [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'HOU': [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'IND': [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'JAX': [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'KC': [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'LV': [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'LAC': [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'LA': [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'MIA': [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'MIN': [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'NE': [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'NO': [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'NYG': [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'NYJ': [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'PHI': [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'PIT': [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'SEA': [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'SF': [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'TB': [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'TEN': [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'WAS': [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
}
